image: tobymellor/php-git-ftp:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - cd wp-content/themes/make-it-all
            - npm install
            - npm test
            - cd ../../.. # back to the base directory
            - git status
            - git ftp push --user $INTEROUTE_USER --passwd $INTEROUTE_PASS sftp://$INTEROUTE_IP/var/www/html