image: tobymellor/php-git-ftp:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - git reset --hard
            - npm test
            - git ftp push --user $INTEROUTE_USER --passwd $INTEROUTE_PASS sftp://$INTEROUTE_IP/var/www/html